### ISSUE TITLE
Selecting Bulldozer does not change cursor

### ISSUE THREAD

**Issue by LReyome254** [BluelightningSC4/Network-Addon-Mod#244] opened 2015-08-07 01:29 UTC
When you select Bulldoze, sometimes the "handle" from the previous thing you did is still on the cursor. That has sometimes contributed to my CTDs. This has existed since 32 and has not been fixed. Has this even been addressed?

Also, why not movies? They are more descriptive then a picture can ever be

**Comment by GanaramInukshuk** [comment] 2015-08-07 01:33
Issue unrelated to NAM 33 devcycle; currently cannot replicate issue.

**Comment by Titanicbuff** [comment] 2015-08-07 01:38
I've had the same thing occur many times- only work around I found was to click on the menu and it goes away.

**Comment by LReyome254** [comment] 2015-08-07 01:41
Try it with the Flexfly, click, construct, select Bulldoze, and witness the Flexfly still on the cursor

**Comment by GanaramInukshuk** [comment] 2015-08-07 01:42
Sounds like an intermittent issue, but it doesn't make it any more important.

**Comment by GanaramInukshuk** [comment] 2015-08-07 01:45
Also, couldn't you press escape before doing that, anyway? Marked as wontfix.

**Comment by memo33** [comment] 2015-08-07 09:20
I cannot replicate this issue and doubt it is caused by anything in the NAM. Try to replicate the issue without having the NAM installed, using highway interchanges, for example.

**Comment by GanaramInukshuk** [comment] 2015-08-07 21:39
I've ended up replicating the issue and with the NAM (possibly has to do with being really deep in the tabs ring and not at the first tab ring entry), but I don't see any way of being able to fix it. Besides, pressing escape before pressing bulldoze fixes the problem, anyway.

Somehow, it's not replicable in all situations given the above hypothesis.

**Comment by jdenm8** [comment] 2015-08-08 04:21
I'm pretty sure it's a game bug. I'm sure I've seen it happen with custom ploppable lots too.

**Comment by GanaramInukshuk** [comment] 2015-08-08 04:39
That just adds to its unfixability.

**Comment by TarkusSC4** [comment] 2015-08-08 08:51
Just tested it with a completely vanilla game, without the NAM.  The Maxis Highway intersections, as shipped with the game, suffer the same issue.  It seems it's endemic to items that involve RUL0-based placement (i.e. any puzzle pieces, starter pieces or FLEX pieces), so no, this is not anything we can fix, and hitting the "Esc" key, as mentioned by Ganaram, is only a very minor inconvenience at worst, 

Issue closed.

**Closed by TarkusSC4** 2015-08-08 08:51 UTC
Labels: DEFCON 5, wontfix
