### ISSUE TITLE
L2 RHW-6S - Drawing A ramps reverts ramp to L0 RHW-2

### ISSUE THREAD

**Issue by LReyome254** [BluelightningSC4/Network-Addon-Mod#245] opened 2015-08-07 01:55 UTC
https://youtu.be/vvqwsou1MuI

Video shows the issue in action. Even placing L2 starters doesn't work properly for overriding the ramp

**Comment by GanaramInukshuk** [comment] 2015-08-07 01:56
Type A1 Ramps do not work on L1-L4 RHW-6S due to their overhangs. Marked as wontfix.

**Comment by TarkusSC4** [comment] 2015-08-07 03:13
Some images of what Ganaram is talking about:

![overhang1](http://i.imgur.com/llxjR3c.jpg)

![overhang2](http://i.imgur.com/DSt63mh.jpg)

The issue isn't as bad as it was before jondor redid the 6S standards for NAM 31, but it's still enough that we have no intent of making these ramps.

Issue closed.

**Closed by TarkusSC4** 2015-08-07 03:13 UTC
Labels: wontfix
